### PR TITLE
add missing modules on standOff odd and update schema

### PR DESCRIPTION
**Pull request by simonmeoni**

### CODE REVIEW

**Comment by laurentromary** [comment]
Which modules are they?

**Comment by simonmeoni** [comment]
these modules : 
- certainty
- drama
- figures
- gaiji
- msdescription
- nets
- spoken
- textcrit
- transcr
- verse
- tagdocs

**Comment by laurentromary** [comment]
En gros, on part de tei_all, c'est ça?

**Comment by simonmeoni** [comment]
oui !

**Pull request merged**
